services:
  init-node:
    image: ghcr.io/input-output-hk/mithril-client:2506.0-2627f17
    entrypoint: /app/bin/entrypoint.sh
    user: "${UID}:${GID}"
    environment:
      NETWORK: $NETWORK
      UNPACK_DIR: /data
    volumes:
      - ./docker/mithril-entrypoint.sh:/app/bin/entrypoint.sh
      - node-db:/data
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:10.4.1
    environment:
      - NETWORK=$NETWORK
    volumes:
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    depends_on:
      init-node:
        condition: service_completed_successfully
  dolos:
    image: ghcr.io/txpipe/dolos:1.0.0-beta.1
    entrypoint: /entrypoint.sh
    environment:
      NETWORK: $NETWORK
    ports:
      - 3010:3010
    volumes:
      - ./docker/dolos-entrypoint.sh:/entrypoint.sh
      - ./docker/dolos-config.toml.tpl:/config.toml.tpl
      - dolos-db:/data
  blockfrost-platform:
    image: ghcr.io/blockfrost/blockfrost-platform:edge
    build:
      context: ./
      target: runtime
      args:
        - GIT_REVISION
    develop:
      watch:
        - action: rebuild
          path: .
    init: true
    restart: on-failure
    ports:
      - 3000:3000
    profiles: [""]
    volumes:
      - node-ipc:/ipc
    entrypoint:
      - /app/blockfrost-platform
      - --secret
      - $SECRET
      - --reward-address
      - $REWARD_ADDRESS
      - --node-socket-path
      - /ipc/node.socket
      - --dolos-endpoint
      - http://dolos:3010
      - --dolos-timeout-sec
      - "30"
  blockfrost-platform-solitary:
    image: ghcr.io/blockfrost/blockfrost-platform:edge
    build:
      context: ./
      target: runtime
    develop:
      watch:
        - action: rebuild
          path: .
    init: true
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - node-ipc:/ipc
    profiles: [solitary]
    entrypoint:
      - /app/blockfrost-platform
      - --solitary
      - --node-socket-path
      - /ipc/node.socket
      - --dolos-endpoint
      - http://dolos:3010
      - --dolos-timeout-sec
      - "30"
volumes:
  node-db:
  node-ipc:
  dolos-db:
