hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
max_width = 100

fn_call_width = 60

match_block_trailing_comma = true

reorder_imports = true
reorder_modules = true

use_try_shorthand = true
use_field_init_shorthand = true
style_edition = "2024"