[upstream]
peer_address = "preprod-node.world.dev.cardano.org:30000"
network_magic = 1
is_testnet = true

[storage]
version = "v1"
path = "data"
max_wal_history = 10000
max_chain_history = 10000

[genesis]
byron_path = "byron.json"
shelley_path = "shelley.json"
alonzo_path = "alonzo.json"
conway_path = "conway.json"

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[serve.ouroboros]
listen_path = "dolos.socket"
magic = 1

[relay]
listen_address = "[::]:30031"
magic = 1

[mithril]
aggregator = "https://aggregator.release-preprod.api.mithril.network/aggregator"
genesis_key = "5b3...45d"                                                        # redacted

[logging]
max_level = "INFO"
include_tokio = false
include_pallas = false
include_grpc = false
