[server]
address = '0.0.0.0:3000'
log_level = 'info'

[database]
connection_string = 'postgresql://user:pass@host:port/db'

[blockfrost]
NFT_policty_id = 'your_policy_id'
project_id = 'BLOCKFROST_PROJECT_ID'
