name: Git Checks
on: [pull_request]
jobs:
  block-fixup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@v2.0.0
      - name: Ensure CHANGELOG.md is updated
        run: |
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          if ! grep <<<"$changed_files" -qE "^CHANGELOG\.md$"; then
            echo fatal: CHANGELOG.md must be updated in each pull request."
            exit 1
          fi
