name: Nix
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            targetSystem: x86_64-linux
          - os: macos-12
            targetSystem: x86_64-darwin
          - os: macos-14
            targetSystem: aarch64-darwin
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            substituters = https://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          upstream-cache: https://cache.iog.io
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Check the repository
        run: nix flake check --show-trace --print-build-logs
      - name: Build the package
        run: nix build --show-trace --print-build-logs .#packages.${{ matrix.targetSystem }}.default
      - name: Build the devshell
        run: nix build --show-trace --print-build-logs .#devShells.${{ matrix.targetSystem }}.default
